CREATE TABLE IF NOT EXISTS kundalis (
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  access_token CHAR(36) NOT NULL,
  full_name VARCHAR(150) NOT NULL,
  gender ENUM('male', 'female', 'other') NULL,
  date_of_birth DATE NOT NULL,
  time_of_birth TIME NOT NULL,
  place_of_birth VARCHAR(255) NOT NULL,
  latitude DECIMAL(9,6) NOT NULL,
  longitude DECIMAL(9,6) NOT NULL,
  timezone VARCHAR(64) NOT NULL,
  utc_offset_minutes INT NOT NULL,
  ayanamsa VARCHAR(50) NOT NULL DEFAULT 'Lahiri',
  language_preference ENUM('en', 'hi', 'mr') NOT NULL DEFAULT 'en',
  lagna VARCHAR(50) NULL,
  rashi VARCHAR(50) NULL,
  nakshatra VARCHAR(50) NULL,
  nakshatra_pada TINYINT UNSIGNED NULL,
  status ENUM('pending', 'completed', 'failed') NOT NULL DEFAULT 'pending',
  raw_response LONGTEXT NULL,
  created_by INT UNSIGNED NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT fk_kundalis_created_by FOREIGN KEY (created_by) REFERENCES users(id) ON DELETE SET NULL,
  UNIQUE KEY uq_kundalis_access_token (access_token),
  KEY idx_kundalis_full_name (full_name),
  KEY idx_kundalis_dob (date_of_birth),
  KEY idx_kundalis_created_at (created_at),
  KEY idx_kundalis_place (place_of_birth)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
