CREATE TABLE IF NOT EXISTS kundali_matches (
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  access_token CHAR(36) NOT NULL,
  groom_name VARCHAR(150) NOT NULL,
  groom_date_of_birth DATE NOT NULL,
  groom_time_of_birth TIME NOT NULL,
  groom_place_of_birth VARCHAR(255) NOT NULL,
  groom_moon_sign VARCHAR(30) NOT NULL,
  groom_nakshatra VARCHAR(30) NOT NULL,
  bride_name VARCHAR(150) NOT NULL,
  bride_date_of_birth DATE NOT NULL,
  bride_time_of_birth TIME NOT NULL,
  bride_place_of_birth VARCHAR(255) NOT NULL,
  bride_moon_sign VARCHAR(30) NOT NULL,
  bride_nakshatra VARCHAR(30) NOT NULL,
  total_score DECIMAL(4,1) NOT NULL,
  max_score TINYINT UNSIGNED NOT NULL DEFAULT 36,
  verdict VARCHAR(100) NOT NULL,
  koota_breakdown JSON NOT NULL,
  created_by INT UNSIGNED NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_matches_created_by FOREIGN KEY (created_by) REFERENCES users(id) ON DELETE SET NULL,
  UNIQUE KEY uq_matches_access_token (access_token),
  KEY idx_matches_created_at (created_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
